### PR TITLE
Added function line().

### PR DESCRIPTION
**Pull request by johnnymast**
Hello,

I have cleaned up your code a litle bit and added the line() function to write an empty line. I am using your amazing class to write an installer for my opensource project. 

There are my changes:

- Added @throws to docblock on setOutputPath
- Removed "@param bool $create" from docblock on setOutputPath
- Changed "@param type $key" to "@param string $key" on get
- Changed "@var type" to "@var string" on variable $outputPath
- Added function line() to we can write text lines 

````PHP
$env = new DotEnvWriter('.env.xx');
$env->line('# THis is awesome!');
$env->set('ENVIRONMENT', 'dev');
```

### CODE REVIEW

**Comment by johnnymast** [comment]
By the way i wanted to write you a new test for line() but the tests fail on windows 10.
See http://pastebin.com/fSHvDQfG

**Comment by davidwoodmansee** [comment]
Thanks for the contribution, it looks like a nice addition. I'll have to look into that Windows 10 issue; the tests seem to run fine on the Linux flavors we use. I've tagged this as the 1.2.0 release. Cheers!

**Comment by johnnymast** [comment]
@davidwoodmansee no problem, i already pulled in version 1.2.0 for my project. I already regret the empty check on the line() function. Now i have to do ->line(' '); :(

**Comment by davidwoodmansee** [comment]
If you want to create another pull request that removes the empty check I would merge that in. I was thinking it could also `return $this;` to keep the fluent interface.

**Comment by davidwoodmansee** [comment]
Actually, what would you think about renaming it to maybe "add" or "append"? I like to try to follow a consistent naming convention and the other main methods are just a verb, e.g. get/set/load

**Comment by davidwoodmansee** [comment]
On second thought, I'm not sure that is as clear as it could be. Maybe addLine or appendLine would be even better.

**Comment by johnnymast** [comment]
Yes i have been thinking for a while to keep it nice and clean and not make it look wierd.

**Comment by davidwoodmansee** [comment]
I pushed some updates tagged v1.2.1. I chose not to rename the line method at this point, so everything should still be compatible with your project. I did remove the `empty` check, and I resolved the line-ending issues that were preventing the tests from succeeding on Windows. If you run into any further issues with that, feel free to let me know. Thanks!

**Comment by johnnymast** [comment]
I will test the tests for you when i get back home. In the Netherlands office hours just started now so i cant test now.

**Pull request merged**
